apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
      spec:
        containers:
          - name: web-server
            image: y16072001001/webserver:latest
            ports:
              - containerPort: 80
